package littlealchemycomb.collections;

import littlealchemycomb.Abstract;
import littlealchemycomb.combination;

import java.util.Scanner;

public class S extends Abstract {
    @Override
    public void alphabet() {
        System.out.println("sack\nsaddle\nsafe\nsafetyglasses\nsailboat\nsailor\nsalt\nsand\nsandcastle\nsandpaper\nsandstone\nsandstorm\nsandwich\nsanta\nsap\nsaturn\nscalpel\nscarecrow\nscience\nscissors\nscorpion\nscubatank\nscythe\nsea\nseagull\nseahorse\nseal\nseaplane\nseasickness\nseaweed\nseed\nsewingmachine\nshark\nsheep\nsheetmusic\nshovel\nshuriken\nsickness\nsilo\nskateboard\nskeleton\nskigoggles\nskier\nsky\nskyscraper\nsleigh\nsloth\nsmall\nsmog\nsmoke\nsmokesignal\nsmoothie\nsnake\nsnow\nsnowglobe\nsnowball\nsnowboard\nsnowboarder\nsnowman\nsnowmobile\nsoap\nsoda\nsoil\nsolarcell\nsolarsystem\nsolid\nsound\nspace\nspacestation\nspaceship\nspaghetti\nsphinx\nspider\nspotlight\nsprinkles\nsquirrel\nstar\nstarfish\nstatue\nsteak\nsteam\nsteamengine\nsteamboat\nsteel\nsteelwool\nstethoscope\nstone\nstorm\nstory\nstream\nstringphone\nstungun\nsugar\nsun\nsundial\nsunflower\nsunglasses\nsupernova\nsurfer\nsushi\nswamp\nsweater\nswimgoggles\nswimmer\nswimmingpool\nsword\nswordfish\nsyringe");
        Scanner input = new Scanner(System.in);
        System.out.println("Enter the word:");
        String m = input.nextLine();
        switch (m){
            case"sack":
                combination.sack();
                break;
            case"saddle":
                combination.saddle();
                break;
            case"safe":
                combination.safe();
                break;
            case"safetyglasses":
                combination.safteyglasses();
                break;
            case"sailboat":
                combination.sailboat();
                break;
            case"sailor":
                combination.sailor();
                break;
            case"salt":
                combination.salt();
                break;
            case"sand":
                combination.sand();
                break;
            case"sandcastle":
                combination.sandcastle();
                break;
            case"sandpaper":
                combination.sandpaper();
                break;
            case"sandstone":
                combination.sandstone();
                break;
            case"sandstorm":
                combination.sandstorm();
                break;
            case"sandwich":
                combination.sandwich();
                break;
            case"santa":
                combination.santa();
                break;
            case"sap":
                combination.sap();
                break;
            case"saturn":
                combination.saturn();
                break;
            case"scalpel":
                combination.scalpel();
                break;
            case"scarecrow":
                combination.scarecrow();
                break;
            case"science":
                combination.science();
                break;
            case"scorpion":
                combination.scorpion();
                break;
            case"scubatank":
                combination.scubatank();
                break;
            case"scissors":
                combination.scissors();
                break;
            case"scythe":
                combination.scythe();
                break;
            case"sea":
                combination.sea();
                break;
            case"seagull":
                combination.seagull();
                break;
            case"seahorse":
                combination.seahorse();
                break;
            case"seal":
                combination.seal();
                break;
            case"seaplane":
                combination.seaplane();
                break;
            case"seasickness":
                combination.seasickness();
                break;
            case"seaweed":
                combination.seaweed();
                break;
            case"seed":
                combination.seed();
                break;
            case"sewingmachine":
                combination.sewingmachine();
                break;
            case"shark":
                combination.shark();
                break;
            case"sheep":
                combination.sheep();
                break;
            case"sheetmusic":
                combination.sheetmusic();
                break;
            case"shovel":
                combination.shovel();
                break;
            case"shuriken":
                combination.shuriken();
                break;
            case"sickness":
                combination.sickness();
                break;
            case"silo":
                combination.silo();
                break;
            case"skateboard":
                combination.skateboard();
                break;
            case"skeleton":
                combination.skeleton();
                break;
            case"skier":
                combination.skier();
                break;
            case"skigoggles":
                combination.skigoggles();
                break;
            case"sky":
                combination.sky();
                break;
            case"skyscrapaper":
                combination.skyscraper();
                break;
            case"sleigh":
                combination.sleigh();
                break;
            case"sloth":
                combination.sloth();
                break;
            case"small":
                combination.small();
                break;
            case"smog":
                combination.smog();
                break;
            case"smoke":
                combination.smoke();
                break;
            case"smokesignal":
                combination.smokesignal();
                break;
            case"smoothie":
                combination.smoothie();
                break;
            case"snake":
                combination.snake();
                break;
            case"snow":
                combination.snow();
                break;
            case"snowball":
                combination.snowball();
                break;
            case"snowboard":
                combination.snowboard();
                break;
            case"snowboader":
                combination.snowboarder();
                break;
            case"snowglobe":
                combination.snowglobe();
                break;
            case"snowman":
                combination.snowman();
                break;
            case"snowmobile":
                combination.snowmobile();
                break;
            case"solarcell":
                combination.solarcell();
                break;
            case"soap":
                combination.soap();
                break;
            case"soda":
                combination.soda();
                break;
            case"soil":
                combination.soil();
                break;
            case"soild":
                combination.soild();
                break;
            case"sollarsystem":
                combination.solarsystem();
                break;
            case"sound":
                combination.sound();
                break;
            case"space":
                combination.space();
                break;
            case"spaceship":
                combination.spaceship();
                break;
            case"spacestation":
                combination.spacestation();
                break;
            case"spaghetti":
                combination.spaghetti();
                break;
            case"sphinx":
                combination.sphinx();
                break;
            case"spider":
                combination.spider();
                break;
            case"spotlight":
                combination.spotlight();
                break;
            case"sprinkles":
                combination.sprinkles();
                break;
            case"squrriel":
                combination.squirrel();
                break;
            case"star":
                combination.star();
                break;
            case"starfish":
                combination.starfish();
                break;
            case"statue":
                combination.statue();
                break;
            case"steak":
                combination.steak();
                break;
            case"steam":
                combination.steam();
                break;
            case"steamboat":
                combination.steamboat();
                break;
            case"steamengine":
                combination.steamengine();
                break;
            case"steel":
                combination.steel();
                break;
            case"steelwool":
                combination.steelwool();
                break;
            case"stethoscope":
                combination.stethoscope();
                break;
            case"stone":
                combination.stone();
                break;
            case"storm":
                combination.storm();
                break;
            case"story":
                combination.story();
                break;
            case"stream":
                combination.stream();
                break;
            case"stringphone":
                combination.stringphone();
                break;
            case"stungun":
                combination.stungun();
                break;
            case"sugar":
                combination.sugar();
                break;
            case"sun":
                combination.sun();
                break;
            case"sundial":
                combination.sundial();
                break;
            case"sunflower":
                combination.sunflower();
                break;
            case"sunglasses":
                combination.sunglasses();
                break;
            case"supernova":
                combination.supernova();
                break;
            case"surfer":
                combination.surfer();
                break;
            case"sushi":
                combination.sushi();
                break;
            case"swap":
                combination.swamp();
                break;
            case"sweater":
                combination.sweater();
                break;
            case"swimgoggles":
                combination.swimgoggles();
                break;
            case"swimmer":
                combination.swimmer();
                break;
            case"swimmingpool":
                combination.swimmingpool();
                break;
            case"sword":
                combination.sword();
                break;
            case"swordfish":
                combination.swordfish();
                break;
            case"syringe":
                combination.syringe();
                break;
        }
    }
}

