package littlealchemycomb.collections;

import littlealchemycomb.Abstract;
import littlealchemycomb.combination;

import java.util.Scanner;

public class S extends Abstract {
    @Override
    public void alphabet() {
        System.out.println("sack\nsaddle\nsafe\nsafetyglasses\nsailboat\nsailor\nsalt\nsand\nsandcastle\nsandpaper\nsandstone\nsandstorm\nsandwich\nsanta\nsap\nsaturn\nscalpel\nscarecrow\nscience\nscissors\nscorpion\nscubatank\nscythe\nsea\nseagull\nseahorse\nseal\nseaplane\nseasickness\nseaweed\nseed\nsewingmachine\nshark\nsheep\nsheetmusic\nshovel\nshuriken\nsickness\nsilo\nskateboard\nskeleton\nskigoggles\nskier\nsky\nskyscraper\nsleigh\nsloth\nsmall\nsmog\nsmoke\nsmokesignal\nsmoothie\nsnake\nsnow\nsnowglobe\nsnowball\nsnowboard\nsnowboarder\nsnowman\nsnowmobile\nsoap\nsoda\nsoil\nsolarcell\nsolarsystem\nsolid\nsound\nspace\nspacestation\nspaceship\nspaghetti\nsphinx\nspider\nspotlight\nsprinkles\nsquirrel\nstar\nstarfish\nstatue\nsteak\nsteam\nsteamengine\nsteamboat\nsteel\nsteelwool\nstethoscope\nstone\nstorm\nstory\nstream\nstringphone\nstungun\nsugar\nsun\nsundial\nsunflower\nsunglasses\nsupernova\nsurfer\nsushi\nswamp\nsweater\nswimgoggles\nswimmer\nswimmingpool\nsword\nswordfish\nsyringe");
        Scanner input = new Scanner(System.in);
        System.out.println("Enter the word:");
        String m = input.nextLine();
        switch (m) {
            case "sack" -> combination.sack();
            case "saddle" -> combination.saddle();
            case "safe" -> combination.safe();
            case "safetyglasses" -> combination.safteyglasses();
            case "sailboat" -> combination.sailboat();
            case "sailor" -> combination.sailor();
            case "salt" -> combination.salt();
            case "sand" -> combination.sand();
            case "sandcastle" -> combination.sandcastle();
            case "sandpaper" -> combination.sandpaper();
            case "sandstone" -> combination.sandstone();
            case "sandstorm" -> combination.sandstorm();
            case "sandwich" -> combination.sandwich();
            case "santa" -> combination.santa();
            case "sap" -> combination.sap();
            case "saturn" -> combination.saturn();
            case "scalpel" -> combination.scalpel();
            case "scarecrow" -> combination.scarecrow();
            case "science" -> combination.science();
            case "scorpion" -> combination.scorpion();
            case "scubatank" -> combination.scubatank();
            case "scissors" -> combination.scissors();
            case "scythe" -> combination.scythe();
            case "sea" -> combination.sea();
            case "seagull" -> combination.seagull();
            case "seahorse" -> combination.seahorse();
            case "seal" -> combination.seal();
            case "seaplane" -> combination.seaplane();
            case "seasickness" -> combination.seasickness();
            case "seaweed" -> combination.seaweed();
            case "seed" -> combination.seed();
            case "sewingmachine" -> combination.sewingmachine();
            case "shark" -> combination.shark();
            case "sheep" -> combination.sheep();
            case "sheetmusic" -> combination.sheetmusic();
            case "shovel" -> combination.shovel();
            case "shuriken" -> combination.shuriken();
            case "sickness" -> combination.sickness();
            case "silo" -> combination.silo();
            case "skateboard" -> combination.skateboard();
            case "skeleton" -> combination.skeleton();
            case "skier" -> combination.skier();
            case "skigoggles" -> combination.skigoggles();
            case "sky" -> combination.sky();
            case "skyscrapaper" -> combination.skyscraper();
            case "sleigh" -> combination.sleigh();
            case "sloth" -> combination.sloth();
            case "small" -> combination.small();
            case "smog" -> combination.smog();
            case "smoke" -> combination.smoke();
            case "smokesignal" -> combination.smokesignal();
            case "smoothie" -> combination.smoothie();
            case "snake" -> combination.snake();
            case "snow" -> combination.snow();
            case "snowball" -> combination.snowball();
            case "snowboard" -> combination.snowboard();
            case "snowboader" -> combination.snowboarder();
            case "snowglobe" -> combination.snowglobe();
            case "snowman" -> combination.snowman();
            case "snowmobile" -> combination.snowmobile();
            case "solarcell" -> combination.solarcell();
            case "soap" -> combination.soap();
            case "soda" -> combination.soda();
            case "soil" -> combination.soil();
            case "soild" -> combination.soild();
            case "sollarsystem" -> combination.solarsystem();
            case "sound" -> combination.sound();
            case "space" -> combination.space();
            case "spaceship" -> combination.spaceship();
            case "spacestation" -> combination.spacestation();
            case "spaghetti" -> combination.spaghetti();
            case "sphinx" -> combination.sphinx();
            case "spider" -> combination.spider();
            case "spotlight" -> combination.spotlight();
            case "sprinkles" -> combination.sprinkles();
            case "squrriel" -> combination.squirrel();
            case "star" -> combination.star();
            case "starfish" -> combination.starfish();
            case "statue" -> combination.statue();
            case "steak" -> combination.steak();
            case "steam" -> combination.steam();
            case "steamboat" -> combination.steamboat();
            case "steamengine" -> combination.steamengine();
            case "steel" -> combination.steel();
            case "steelwool" -> combination.steelwool();
            case "stethoscope" -> combination.stethoscope();
            case "stone" -> combination.stone();
            case "storm" -> combination.storm();
            case "story" -> combination.story();
            case "stream" -> combination.stream();
            case "stringphone" -> combination.stringphone();
            case "stungun" -> combination.stungun();
            case "sugar" -> combination.sugar();
            case "sun" -> combination.sun();
            case "sundial" -> combination.sundial();
            case "sunflower" -> combination.sunflower();
            case "sunglasses" -> combination.sunglasses();
            case "supernova" -> combination.supernova();
            case "surfer" -> combination.surfer();
            case "sushi" -> combination.sushi();
            case "swap" -> combination.swamp();
            case "sweater" -> combination.sweater();
            case "swimgoggles" -> combination.swimgoggles();
            case "swimmer" -> combination.swimmer();
            case "swimmingpool" -> combination.swimmingpool();
            case "sword" -> combination.sword();
            case "swordfish" -> combination.swordfish();
            case "syringe" -> combination.syringe();
        }
    }
}

